name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-run-unit-tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: xcode-select -s /Applications/Xcode_15.0.1.app
    - name: Build
      run: xcodebuild build -scheme CCMenu -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run unit tests
      run: xcodebuild test -scheme CCMenu -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
  run-uitests:
    needs: build-and-run-unit-tests
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: xcode-select -s /Applications/Xcode_15.0.1.app
    - name: Run UI tests
      run: xcodebuild test -scheme CCMenu.UITests -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}

