name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-run-unit-tests:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild build -scheme CCMenu  -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
#   - name: Run unit tests
#     run: xcodebuild test -scheme CCMenu  -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}
# run-uitests:
#   needs: build-and-run-unit-tests
#   runs-on: macOS-latest
#   steps:
#   - uses: actions/checkout@v3
#   - name: Run UI tests
#     run: xcodebuild test -scheme CCMenu.UITests  -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}

